
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                0
#define PARTNER_STEVEN              1
#define PARTNER_EMMIE               2
#define PARTNER_TABITHA             3
#define PARTNER_MATT                4
#define PARTNER_SHELLY_JAGGED_PASS  5
#define PARTNER_ARCHIE_MT_PYRE      6
#define PARTNER_MAXIE_MT_PYRE       7
#define PARTNER_ARCHIE_SKY_PILLAR   8
#define PARTNER_MAXIE_SKY_PILLAR    9
#define PARTNER_SHELLY_MHO          10
#define PARTNER_STEVEN_TWELVE       11
#define PARTNER_STEVEN_B2B          12
#define PARTNER_BLUE_TWELVE         13
#define PARTNER_BLUE_B2B            14
#define PARTNER_SHELLY_MHO_BOSS     15
#define PARTNER_TABITHA_AHO_BOSS    16
#define PARTNER_BROCK_MOSSDEEP      17
#define PARTNER_MISTY_MOSSDEEP      18
#define PARTNER_SURGE_MOSSDEEP      19
#define PARTNER_ERIKA_MOSSDEEP      20
#define PARTNER_JANINE_SKY_PILLAR   21
#define PARTNER_KOGA_SKY_PILLAR     22
#define PARTNER_SABRINA_SKY_PILLAR  23
#define PARTNER_BLAINE_SKY_PILLAR   24
#define PARTNER_SABRINA_MOSSDEEP    25
#define PARTNER_TATE_MOSSDEEP       26
#define PARTNER_LIZA_MOSSDEEP       27
#define PARTNER_LORELEI_MOSSDEEP    28
#define PARTNER_BRUNO_MOSSDEEP      29
#define PARTNER_AGATHA_MOSSDEEP     30
#define PARTNER_LANCE_MOSSDEEP      31
#define PARTNER_BIRCH               32
#define PARTNER_COUNT               33

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
