#ifndef GUARD_CONSTANTS_BATTLE_POOL_H
#define GUARD_CONSTANTS_BATTLE_POOL_H

enum PoolStyle {
    POOL_STYLE_NONE,
    POOL_STYLE_PREPARATION,
    POOL_STYLE_SLOW_STEADY,
    POOL_STYLE_ENDURANCE,
    POOL_STYLE_HIGH_RISK,
    POOL_STYLE_WEAKENING,
    POOL_STYLE_UNPREDICTABLE,
    POOL_STYLE_WEATHER,
    POOL_NUM_STYLES
};

#define BATTLE_POOL_FUNC_INIT                    0
#define BATTLE_POOL_FUNC_GET_DATA                1
#define BATTLE_POOL_FUNC_SET_DATA                2
#define BATTLE_POOL_FUNC_SAVE                    3
#define BATTLE_POOL_FUNC_NULL                    4
#define BATTLE_POOL_FUNC_NULL2                   5
#define BATTLE_POOL_FUNC_SELECT_RENT_MONS        6
#define BATTLE_POOL_FUNC_SWAP_RENT_MONS          7
#define BATTLE_POOL_FUNC_SET_SWAPPED             8
#define BATTLE_POOL_FUNC_SET_OPPONENT_MONS       9
#define BATTLE_POOL_FUNC_SET_PARTIES             10
#define BATTLE_POOL_FUNC_SET_OPPONENT_GFX        11
#define BATTLE_POOL_FUNC_GENERATE_OPPONENT_MONS  12
#define BATTLE_POOL_FUNC_GENERATE_RENTAL_MONS    13
#define BATTLE_POOL_FUNC_GET_OPPONENT_MON_TYPE   14
#define BATTLE_POOL_FUNC_GET_OPPONENT_STYLE      15
#define BATTLE_POOL_FUNC_RESET_HELD_ITEMS        16

#define POOL_DATA_WIN_STREAK         1
#define POOL_DATA_WIN_STREAK_ACTIVE  2
#define POOL_DATA_WIN_STREAK_SWAPS   3

#endif // GUARD_CONSTANTS_BATTLE_POOL_H
