#ifndef GUARD_CONSTANTS_SONGS_H
#define GUARD_CONSTANTS_SONGS_H

// Original JP names listed on right, along with any additional notes

enum __attribute__((packed)) SongId
{
    MUS_DUMMY,
    SE_USE_ITEM,
    SE_PC_LOGIN,
    SE_PC_OFF,
    SE_PC_ON,
    SE_SELECT,
    SE_WIN_OPEN,
    SE_WALL_HIT,
    SE_DOOR,
    SE_EXIT,
    SE_LEDGE,
    SE_BIKE_BELL,
    SE_NOT_EFFECTIVE,
    SE_EFFECTIVE,
    SE_SUPER_EFFECTIVE,
    SE_BALL_OPEN,
    SE_FAINT,
    SE_FLEE,
    SE_SLIDING_DOOR,
    SE_SHIP,
    SE_BANG,
    SE_PIN,
    SE_BOO,
    SE_BALL,
    SE_CONTEST_PLACE,
    SE_A,
    SE_I,
    SE_U,
    SE_E,
    SE_O,
    SE_N,
    SE_SUCCESS,
    SE_FAILURE,
    SE_EXP,
    SE_BIKE_HOP,
    SE_SWITCH,
    SE_CLICK,
    SE_FU_ZAKU,
    SE_CONTEST_CONDITION_LOSE,
    SE_LAVARIDGE_FALL_WARP,
    SE_ICE_STAIRS,
    SE_ICE_BREAK,
    SE_ICE_CRACK,
    SE_FALL,
    SE_UNLOCK,
    SE_WARP_IN,
    SE_WARP_OUT,
    SE_REPEL,
    SE_ROTATING_GATE,
    SE_TRUCK_MOVE,
    SE_TRUCK_STOP,
    SE_TRUCK_UNLOAD,
    SE_TRUCK_DOOR,
    SE_BERRY_BLENDER,
    SE_CARD,
    SE_SAVE,
    SE_BALL_BOUNCE_1,
    SE_BALL_BOUNCE_2,
    SE_BALL_BOUNCE_3,
    SE_BALL_BOUNCE_4,
    SE_BALL_TRADE,
    SE_BALL_THROW,
    SE_NOTE_C,
    SE_NOTE_D,
    SE_NOTE_E,
    SE_NOTE_F,
    SE_NOTE_G,
    SE_NOTE_A,
    SE_NOTE_B,
    SE_NOTE_C_HIGH,
    SE_PUDDLE,
    SE_BRIDGE_WALK,
    SE_ITEMFINDER,
    SE_DING_DONG,
    SE_BALLOON_RED,
    SE_BALLOON_BLUE,
    SE_BALLOON_YELLOW,
    SE_BREAKABLE_DOOR,
    SE_MUD_BALL,
    SE_FIELD_POISON,
    SE_ESCALATOR,
    SE_THUNDERSTORM,
    SE_THUNDERSTORM_STOP,
    SE_DOWNPOUR,
    SE_DOWNPOUR_STOP,
    SE_RAIN,
    SE_RAIN_STOP,
    SE_THUNDER,
    SE_THUNDER2,
    SE_ELEVATOR,
    SE_LOW_HEALTH,
    SE_EXP_MAX,
    SE_ROULETTE_BALL,
    SE_ROULETTE_BALL2,
    SE_TAILLOW_WING_FLAP,
    SE_SHOP,
    SE_CONTEST_HEART,
    SE_CONTEST_CURTAIN_RISE,
    SE_CONTEST_CURTAIN_FALL,
    SE_CONTEST_ICON_CHANGE,
    SE_CONTEST_ICON_CLEAR,
    SE_CONTEST_MONS_TURN,
    SE_SHINY,
    SE_INTRO_BLAST,
    SE_MUGSHOT,
    SE_APPLAUSE,
    SE_VEND,
    SE_ORB,
    SE_DEX_SCROLL,
    SE_DEX_PAGE,
    SE_POKENAV_ON,
    SE_POKENAV_OFF,
    SE_DEX_SEARCH,
    SE_EGG_HATCH,
    SE_BALL_TRAY_ENTER,
    SE_BALL_TRAY_BALL,
    SE_BALL_TRAY_EXIT,
    SE_GLASS_FLUTE,
    SE_M_THUNDERBOLT, // Move SFX
    SE_M_THUNDERBOLT2,
    SE_M_HARDEN,
    SE_M_NIGHTMARE,
    SE_M_VITAL_THROW,
    SE_M_VITAL_THROW2,
    SE_M_BUBBLE,
    SE_M_BUBBLE2,
    SE_M_BUBBLE3,
    SE_M_RAIN_DANCE,
    SE_M_CUT,
    SE_M_STRING_SHOT,
    SE_M_STRING_SHOT2,
    SE_M_ROCK_THROW,
    SE_M_GUST,
    SE_M_GUST2,
    SE_M_DOUBLE_SLAP,
    SE_M_DOUBLE_TEAM,
    SE_M_RAZOR_WIND,
    SE_M_ICY_WIND,
    SE_M_THUNDER_WAVE,
    SE_M_COMET_PUNCH,
    SE_M_MEGA_KICK,
    SE_M_MEGA_KICK2,
    SE_M_CRABHAMMER,
    SE_M_JUMP_KICK,
    SE_M_FLAME_WHEEL,
    SE_M_FLAME_WHEEL2,
    SE_M_FLAMETHROWER,
    SE_M_FIRE_PUNCH,
    SE_M_TOXIC,
    SE_M_SACRED_FIRE,
    SE_M_SACRED_FIRE2,
    SE_M_EMBER,
    SE_M_TAKE_DOWN,
    SE_M_BLIZZARD,
    SE_M_BLIZZARD2,
    SE_M_SCRATCH,
    SE_M_VICEGRIP,
    SE_M_WING_ATTACK,
    SE_M_FLY,
    SE_M_SAND_ATTACK,
    SE_M_RAZOR_WIND2,
    SE_M_BITE,
    SE_M_HEADBUTT,
    SE_M_SURF,
    SE_M_HYDRO_PUMP,
    SE_M_WHIRLPOOL,
    SE_M_HORN_ATTACK,
    SE_M_TAIL_WHIP,
    SE_M_MIST,
    SE_M_POISON_POWDER,
    SE_M_BIND,
    SE_M_DRAGON_RAGE,
    SE_M_SING,
    SE_M_PERISH_SONG,
    SE_M_PAY_DAY,
    SE_M_DIG,
    SE_M_DIZZY_PUNCH,
    SE_M_SELF_DESTRUCT,
    SE_M_EXPLOSION,
    SE_M_ABSORB_2,
    SE_M_ABSORB,
    SE_M_SCREECH,
    SE_M_BUBBLE_BEAM,
    SE_M_BUBBLE_BEAM2,
    SE_M_SUPERSONIC,
    SE_M_BELLY_DRUM,
    SE_M_METRONOME,
    SE_M_BONEMERANG,
    SE_M_LICK,
    SE_M_PSYBEAM,
    SE_M_FAINT_ATTACK,
    SE_M_SWORDS_DANCE,
    SE_M_LEER,
    SE_M_SWAGGER,
    SE_M_SWAGGER2,
    SE_M_HEAL_BELL,
    SE_M_CONFUSE_RAY,
    SE_M_SNORE,
    SE_M_BRICK_BREAK,
    SE_M_GIGA_DRAIN,
    SE_M_PSYBEAM2,
    SE_M_SOLAR_BEAM,
    SE_M_PETAL_DANCE,
    SE_M_TELEPORT,
    SE_M_MINIMIZE,
    SE_M_SKETCH,
    SE_M_SWIFT,
    SE_M_REFLECT,
    SE_M_BARRIER,
    SE_M_DETECT,
    SE_M_LOCK_ON,
    SE_M_MOONLIGHT,
    SE_M_CHARM,
    SE_M_CHARGE,
    SE_M_STRENGTH,
    SE_M_HYPER_BEAM,
    SE_M_WATERFALL,
    SE_M_REVERSAL,
    SE_M_ACID_ARMOR,
    SE_M_SANDSTORM,
    SE_M_TRI_ATTACK,
    SE_M_TRI_ATTACK2,
    SE_M_ENCORE,
    SE_M_ENCORE2,
    SE_M_BATON_PASS,
    SE_M_MILK_DRINK,
    SE_M_ATTRACT,
    SE_M_ATTRACT2,
    SE_M_MORNING_SUN,
    SE_M_FLATTER,
    SE_M_SAND_TOMB,
    SE_M_GRASSWHISTLE,
    SE_M_SPIT_UP,
    SE_M_DIVE,
    SE_M_EARTHQUAKE,
    SE_M_TWISTER,
    SE_M_SWEET_SCENT,
    SE_M_YAWN,
    SE_M_SKY_UPPERCUT,
    SE_M_STAT_INCREASE,
    SE_M_HEAT_WAVE,
    SE_M_UPROAR,
    SE_M_HAIL,
    SE_M_COSMIC_POWER,
    SE_M_TEETER_DANCE,
    SE_M_STAT_DECREASE,
    SE_M_HAZE,
    SE_M_HYPER_BEAM2,
    SE_RG_DOOR, // FRLG SFX
    SE_RG_CARD_FLIP,
    SE_RG_CARD_FLIPPING,
    SE_RG_CARD_OPEN,
    SE_RG_BAG_CURSOR,
    SE_RG_BAG_POCKET,
    SE_RG_BALL_CLICK,
    SE_RG_SHOP,
    SE_RG_SS_ANNE_HORN,
    SE_RG_HELP_OPEN,
    SE_RG_HELP_CLOSE,
    SE_RG_HELP_ERROR,
    SE_RG_DEOXYS_MOVE,
    SE_RG_POKE_JUMP_SUCCESS,
    SE_RG_POKE_JUMP_FAILURE,
    SE_POKENAV_CALL, // New Emerald SFX
    SE_POKENAV_HANG_UP,
    SE_ARENA_TIMEUP1,
    SE_ARENA_TIMEUP2,
    SE_PIKE_CURTAIN_CLOSE,
    SE_PIKE_CURTAIN_OPEN,
    SE_SUDOWOODO_SHAKE,
    SE_M_HYPER_BEAM_GEN1,

// Music
    MUS_LITTLEROOT_TEST = 350,
    MUS_GSC_ROUTE38,
    MUS_CAUGHT,
    MUS_VICTORY_WILD,
    MUS_VICTORY_GYM_LEADER,
    MUS_VICTORY_LEAGUE,
    MUS_C_COMM_CENTER,
    MUS_GSC_PEWTER,
    MUS_C_VS_LEGEND_BEAST,
    MUS_ROUTE101,
    MUS_ROUTE110,
    MUS_ROUTE120,
    MUS_PETALBURG,
    MUS_OLDALE,
    MUS_GYM,
    MUS_SURF,
    MUS_PETALBURG_WOODS,
    MUS_LEVEL_UP,
    MUS_HEAL,
    MUS_OBTAIN_BADGE,
    MUS_OBTAIN_ITEM,
    MUS_EVOLVED,
    MUS_OBTAIN_TMHM,
    MUS_LILYCOVE_MUSEUM,
    MUS_ROUTE122,
    MUS_OCEANIC_MUSEUM,
    MUS_EVOLUTION_INTRO,
    MUS_EVOLUTION,
    MUS_MOVE_DELETED,
    MUS_ENCOUNTER_GIRL,
    MUS_ENCOUNTER_MALE,
    MUS_ABANDONED_SHIP,
    MUS_FORTREE,
    MUS_BIRCH_LAB,
    MUS_B_TOWER_RS,
    MUS_ENCOUNTER_SWIMMER,
    MUS_CAVE_OF_ORIGIN,
    MUS_OBTAIN_BERRY,
    MUS_AWAKEN_LEGEND,
    MUS_SLOTS_JACKPOT,
    MUS_SLOTS_WIN,
    MUS_TOO_BAD,
    MUS_ROULETTE,
    MUS_LINK_CONTEST_P1,
    MUS_LINK_CONTEST_P2,
    MUS_LINK_CONTEST_P3,
    MUS_LINK_CONTEST_P4,
    MUS_ENCOUNTER_RICH,
    MUS_VERDANTURF,
    MUS_RUSTBORO,
    MUS_POKE_CENTER,
    MUS_ROUTE104,
    MUS_ROUTE119,
    MUS_CYCLING,
    MUS_POKE_MART,
    MUS_LITTLEROOT,
    MUS_MT_CHIMNEY,
    MUS_ENCOUNTER_FEMALE,
    MUS_LILYCOVE,
    MUS_DESERT,
    MUS_HELP,
    MUS_UNDERWATER,
    MUS_VICTORY_TRAINER,
    MUS_TITLE,
    MUS_INTRO,
    MUS_ENCOUNTER_MAY,
    MUS_ENCOUNTER_INTENSE,
    MUS_ENCOUNTER_COOL,
    MUS_ROUTE113,
    MUS_ENCOUNTER_AQUA,
    MUS_FOLLOW_ME,
    MUS_ENCOUNTER_BRENDAN,
    MUS_EVER_GRANDE,
    MUS_ENCOUNTER_SUSPICIOUS,
    MUS_VICTORY_AQUA_MAGMA,
    MUS_CABLE_CAR,
    MUS_GAME_CORNER,
    MUS_DEWFORD,
    MUS_SAFARI_ZONE,
    MUS_VICTORY_ROAD,
    MUS_AQUA_MAGMA_HIDEOUT,
    MUS_SAILING,
    MUS_MT_PYRE,
    MUS_SLATEPORT,
    MUS_MT_PYRE_EXTERIOR,
    MUS_SCHOOL,
    MUS_HALL_OF_FAME,
    MUS_FALLARBOR,
    MUS_SEALED_CHAMBER,
    MUS_CONTEST_WINNER,
    MUS_CONTEST,
    MUS_ENCOUNTER_MAGMA,
    MUS_INTRO_BATTLE,
    MUS_ABNORMAL_WEATHER,
    MUS_WEATHER_GROUDON,
    MUS_SOOTOPOLIS,
    MUS_CONTEST_RESULTS,
    MUS_HALL_OF_FAME_ROOM,
    MUS_TRICK_HOUSE,
    MUS_ENCOUNTER_TWINS,
    MUS_ENCOUNTER_ELITE_FOUR,
    MUS_ENCOUNTER_HIKER,
    MUS_CONTEST_LOBBY,
    MUS_ENCOUNTER_INTERVIEWER,
    MUS_ENCOUNTER_CHAMPION,
    MUS_CREDITS,
    MUS_END,
    MUS_B_FRONTIER,
    MUS_B_ARENA,
    MUS_OBTAIN_B_POINTS,
    MUS_REGISTER_MATCH_CALL,
    MUS_B_PYRAMID,
    MUS_B_PYRAMID_TOP,
    MUS_B_PALACE,
    MUS_RAYQUAZA_APPEARS,
    MUS_B_TOWER,
    MUS_OBTAIN_SYMBOL,
    MUS_B_DOME,
    MUS_B_PIKE,
    MUS_B_FACTORY,
    MUS_VS_RAYQUAZA,
    MUS_VS_FRONTIER_BRAIN,
    MUS_VS_MEW,
    MUS_B_DOME_LOBBY,
    MUS_VS_WILD,
    MUS_VS_AQUA_MAGMA,
    MUS_VS_TRAINER,
    MUS_VS_GYM_LEADER,
    MUS_VS_CHAMPION,
    MUS_VS_REGI,
    MUS_VS_KYOGRE_GROUDON,
    MUS_VS_RIVAL,
    MUS_VS_ELITE_FOUR,
    MUS_VS_AQUA_MAGMA_LEADER,
    MUS_RG_FOLLOW_ME, // FRLG Music
    MUS_RG_GAME_CORNER,
    MUS_RG_ROCKET_HIDEOUT,
    MUS_RG_GYM,
    MUS_RG_JIGGLYPUFF,
    MUS_RG_INTRO_FIGHT,
    MUS_RG_TITLE,
    MUS_RG_CINNABAR,
    MUS_RG_LAVENDER,
    MUS_RG_HEAL,
    MUS_RG_CYCLING,
    MUS_RG_ENCOUNTER_ROCKET,
    MUS_RG_ENCOUNTER_GIRL,
    MUS_RG_ENCOUNTER_BOY,
    MUS_RG_HALL_OF_FAME,
    MUS_RG_VIRIDIAN_FOREST,
    MUS_RG_MT_MOON,
    MUS_RG_POKE_MANSION,
    MUS_RG_CREDITS,
    MUS_RG_ROUTE1,
    MUS_RG_ROUTE24,
    MUS_RG_ROUTE3,
    MUS_RG_ROUTE11,
    MUS_RG_VICTORY_ROAD,
    MUS_RG_VS_GYM_LEADER,
    MUS_RG_VS_TRAINER,
    MUS_RG_VS_WILD,
    MUS_RG_VS_CHAMPION,
    MUS_RG_PALLET,
    MUS_RG_OAK_LAB,
    MUS_RG_OAK,
    MUS_RG_POKE_CENTER,
    MUS_RG_SS_ANNE,
    MUS_RG_SURF,
    MUS_RG_POKE_TOWER,
    MUS_RG_SILPH,
    MUS_RG_FUCHSIA,
    MUS_RG_CELADON,
    MUS_RG_VICTORY_TRAINER,
    MUS_RG_VICTORY_WILD,
    MUS_RG_VICTORY_GYM_LEADER,
    MUS_RG_VERMILLION,
    MUS_RG_PEWTER,
    MUS_RG_ENCOUNTER_RIVAL,
    MUS_RG_RIVAL_EXIT,
    MUS_RG_DEX_RATING,
    MUS_RG_OBTAIN_KEY_ITEM,
    MUS_RG_CAUGHT_INTRO,
    MUS_RG_PHOTO,
    MUS_RG_GAME_FREAK,
    MUS_RG_CAUGHT,
    MUS_RG_NEW_GAME_INSTRUCT,
    MUS_RG_NEW_GAME_INTRO,
    MUS_RG_NEW_GAME_EXIT,
    MUS_RG_POKE_JUMP,
    MUS_RG_UNION_ROOM,
    MUS_RG_NET_CENTER,
    MUS_RG_MYSTERY_GIFT,
    MUS_RG_BERRY_PICK,
    MUS_RG_SEVII_CAVE,
    MUS_RG_TEACHY_TV_SHOW,
    MUS_RG_SEVII_ROUTE,
    MUS_RG_SEVII_DUNGEON,
    MUS_RG_SEVII_123,
    MUS_RG_SEVII_45,
    MUS_RG_SEVII_67,
    MUS_RG_POKE_FLUTE,
    MUS_RG_VS_DEOXYS,
    MUS_RG_VS_MEWTWO,
    MUS_RG_VS_LEGEND,
    MUS_RG_ENCOUNTER_GYM_LEADER,
    MUS_RG_ENCOUNTER_DEOXYS,
    MUS_RG_TRAINER_TOWER,
    MUS_RG_SLOW_PALLET,
    MUS_RG_TEACHY_TV_MENU,
    MUS_VS_SINNOH_BRAIN = 610,
    MUS_HG_VS_GYM_LEADER = 611, //UNUSED
    MUS_HG_VS_GYM_LEADER_KANTO = 612, //UNUSED
    MUS_HG_VS_ROCKET = 613,
    MUS_HG_VS_CHAMPION = 614, //UNUSED
    MUS_HG_VS_FRONTIER_BRAIN = 615, //UNUSED
    MUS_HG_VICTORY_FRONTIER_BRAIN = 616, //UNUSED
    MUS_VS_KANTONIAN = 617, //UNUSED
    MUS_ACCUMULA_TOWN = 618, //UNUSED
    MUS_AGATE_VILLAGE = 619,
    MUS_AREA_ZERO = 620, //UNUSED
    MUS_AZALEA_TOWN = 621,
    MUS_BATTLE_ARCADE = 622, //UNUSED
    MUS_BATTLE_HALL = 623,
    MUS_BICYCLE = 624,
    MUS_BURNED_TOWER = 625,
    MUS_CANALAVE_CITY = 626, //UNUSED
    MUS_CIANWOOD_CITY = 627,
    MUS_DANCE_THEATRE = 628, //UNUSED
    MUS_DRAGONS_DEN = 629,
    MUS_DRAGONSPIRAL_TOWER = 630,
    MUS_DREAMYARD = 631, //UNUSED
    MUS_DRIFTVEIL_CITY = 632, //UNUSED
    MUS_ECRUTEAK_CITY = 633, //UNUSED
    MUS_ENCOUNTER_GALACTIC_GRUNT = 634, //UNUSED
    MUS_ENCOUNTER_HOOH = 635, //UNUSED
    MUS_ENCOUNTER_KIMONO_GIRL = 636, //UNUSED
    MUS_ENCOUNTER_LOOKER = 637, //UNUSED
    MUS_ENCOUNTER_LUGIA = 638, //UNUSED
    MUS_ENCOUNTER_TEAM_PLASMA = 639, //UNUSED
    MUS_ENCOUNTER_TEAM_PLASMA_2 = 640, //UNUSED
    MUS_ETERNA_CITY = 641,
    MUS_ETERNA_FOREST = 642,
    MUS_FLOAROMA_TOWN = 643,
    MUS_FLOCCESY_TOWN = 644,
    MUS_GALACTIC_HQ = 645, //UNUSED
    MUS_GLOBAL_TERMINAL = 646, //UNUSED
    MUS_GOLENROD_CITY = 647, //UNUSED
    MUS_GREAT_CANYON = 648, //UNUSED
    MUS_HUMILAU_GYM = 649, //UNUSED
    MUS_JOHTO_ROUTE_29 = 650, //UNUSED
    MUS_JOHTO_ROUTE_30 = 651, //UNUSED
    MUS_JOHTO_ROUTE_34 = 652, //UNUSED
    MUS_JUBILIFE_CITY = 653,
    MUS_JUBILIFE_VILLAGE = 654,
    MUS_LAVENDER_TOWN = 655, //UNUSED
    MUS_MEZAGOZA = 656, //UNUSED
    MUS_MIROR_B = 657,
    MUS_MISTRALTON_CITY = 658, //UNUSED
    MUS_MT_CORONET = 659,
    MUS_N_FAREWELL = 660, //UNUSED
    MUS_N_FINAL_BATTLE = 661,
    MUS_OLD_CHATEAU = 662,
    MUS_OPELUCID_CITY = 663, //UNUSED
    MUS_OREBURGH_CITY = 664,
    MUS_ROWANS_LAB = 665,
    MUS_SINJOH_RUINS = 666, //UNUSED
    MUS_SINNOH_LAKE = 667, //UNUSED
    MUS_SINNOH_PKMN_LEAGUE_EXTERIOR = 668,
    MUS_SINNOH_PKMN_LEAGUE_INTERIOR = 669, //UNUSED
    MUS_SINNOH_ROUTE_205 = 670,
    MUS_SINNOH_ROUTE_210 = 671,
    MUS_SINNOH_ROUTE_213 = 672,
    MUS_SKY_TOWER = 673,
    MUS_STRANGE_HOUSE = 674,
    MUS_SUNNYSHORE_CITY = 675,
    MUS_TWINLEAF_TOWN = 676,
    MUS_UNOVA_GYM = 677,
    MUS_UNOVA_ROUTE_4 = 678, //UNUSED
    MUS_UNOVA_ROUTE_6 = 679, //UNUSED
    MUS_UNWAVERING_EMOTIONS = 680, //UNUSED
    MUS_VEILSTONE_CITY = 681,
    MUS_VICTORY_GALACTIC_GRUNT = 682, //UNUSED
    MUS_VICTORY_POKEMON_SINNOH = 683, //UNUSED
    MUS_VICTORY_UNOVA_LEADER = 684, //UNUSED
    MUS_VICTORY_WILD_POKEMON = 685, //UNUSED
    MUS_VS_CIPHER_PEON = 686,
    MUS_VS_COLOSSEUM_ROUND_3 = 687,
    MUS_VS_CYRUS = 688, //UNUSED
    MUS_VS_ENTEI = 689,
    MUS_VS_FINAL_POKEMON = 690,
    MUS_VS_GALACTIC_GRUNT = 691, //UNUSED
    MUS_VS_GHETSIS = 692, //UNUSED
    MUS_VS_GIRATINA = 693, //UNUSED
    MUS_VS_HOOH = 694, //UNUSED
    MUS_VS_IRIS = 695, //UNUSED
    MUS_VS_JOHTO_LEADER = 696, //UNUSED
    MUS_VS_JOHTO_TRAINER = 697,
    MUS_VS_KANTO_TRAINER = 698,
    MUS_VS_LUGIA = 699, //UNUSED
    MUS_VS_POKEMON_AREA_ZERO = 700, //UNUSED
    MUS_VS_POKEMON_JOHTO = 701,
    MUS_VS_POKEMON_KANTO = 702,
    MUS_VS_POKEMON_UNOVA = 703,
    MUS_VS_RAIKOU = 704,
    MUS_VS_ROAMING_LEGENDARY = 705, //UNUSED
    MUS_VS_ROCKET = 706, //UNUSED
    MUS_VS_SILVER = 707,
    MUS_VS_SINNOH_TRAINER = 708,
    MUS_VS_SUICUNE = 709,
    MUS_VS_UNOVA_ELITE_FOUR = 710,
    MUS_VS_UNOVA_LEADER = 711,
    MUS_VS_UNOVA_RIVAL = 712,
    MUS_VS_UNOVA_TRAINER = 713,
    MUS_GS_1 = 714, //UNUSED
    MUS_GS_10 = 715, //UNUSED
    MUS_GS_12 = 716, //UNUSED
    MUS_GS_27 = 717, //UNUSED
    MUS_GS_29 = 718,
    MUS_GS_30 = 719,
    MUS_GS_36 = 720,
    MUS_GS_38 = 721,
    MUS_GS_42 = 722, //UNUSED
    MUS_GS_AROUND = 723,
    MUS_GS_AZALEA = 724,
    MUS_GS_BADGE = 725, //UNUSED
    MUS_GS_BATTLE1 = 726,
    MUS_GS_BATTLE2 = 727,
    MUS_GS_BATTLE3 = 728,
    MUS_GS_VS_JOHTO_LEADER = 729,
    MUS_GS_BATTLE5 = 730, //UNUSED
    MUS_GS_BATTLE6 = 731, //UNUSED
    MUS_GS_BATTLE7 = 732,
    MUS_GS_BATTLE8 = 733,
    MUS_GS_VS_KANTO_LEADER = 734,
    MUS_GS_BIKE = 735,
    MUS_GS_CAUGHT = 736, //UNUSED
    MUS_GS_CAVE1 = 737,
    MUS_GS_CAVE2 = 738, //UNUSED
    MUS_GS_CELADON = 739, //UNUSED
    MUS_GS_CENTER = 740,
    MUS_GS_CHERRYGROVE = 741,
    MUS_GS_CONTEST = 742,
    MUS_GS_CORNER = 743, //UNUSED
    MUS_GS_CORNERLEAVE = 744, //UNUSED
    MUS_GS_CREDITS = 745, //UNUSED
    MUS_GS_DANCE = 746, //UNUSED
    MUS_GS_DELETE = 747, //UNUSED
    MUS_GS_DEN = 748,
    MUS_GS_ECRUTEAK = 749,
    MUS_GS_EGG = 750, //UNUSED
    MUS_GS_ENC1 = 751, //UNUSED
    MUS_GS_ENC2 = 752, //UNUSED
    MUS_GS_ENC3 = 753, //UNUSED
    MUS_GS_ENC4 = 754, //UNUSED
    MUS_GS_ENC5 = 755, //UNUSED
    MUS_GS_ENC6 = 756, //UNUSED
    MUS_GS_ENC7 = 757, //UNUSED
    MUS_GS_ENC8 = 758, //UNUSED
    MUS_GS_ENC9 = 759, //UNUSED
    MUS_GS_ENTRANCE = 760, //UNUSED
    MUS_GS_EVOLVING = 761, //UNUSED
    MUS_GS_FOREST = 762,
    MUS_GS_GOLDENROD = 763,
    MUS_GS_GYM = 764,
    MUS_GS_HALL = 765, //UNUSED
    MUS_GS_HEAL = 766, //UNUSED
    MUS_GS_HIDEOUT = 767,
    MUS_GS_HMTM = 768, //UNUSED
    MUS_GS_INDIGO = 769,
    MUS_GS_INTRO1 = 770, //UNUSED
    MUS_GS_INTRO2 = 771, //UNUSED
    MUS_GS_ITEM1 = 772, //UNUSED
    MUS_GS_ITEM2 = 773, //UNUSED
    MUS_GS_LAB = 774,
    MUS_GS_LAVENDER = 775, //UNUSED
    MUS_GS_LEVELUP = 776, //UNUSED
    MUS_GS_LIGHTHOUSE = 777, //UNUSED
    MUS_GS_MAGNET = 778, //UNUSED
    MUS_GS_MENU = 779, //UNUSED
    MUS_GS_MOM = 780,
    MUS_GS_MTMOON = 781, //UNUSED
    MUS_GS_NEWBARK = 782,
    MUS_GS_OAK = 783, //UNUSED
    MUS_GS_PALLET = 784,
    MUS_GS_PARK = 785, //UNUSED
    MUS_GS_PHONE = 786, //UNUSED
    MUS_GS_POKEDEX1 = 787, //UNUSED
    MUS_GS_POKEDEX2 = 788, //UNUSED
    MUS_GS_RADIO = 789,
    MUS_GS_RADIOFLUTE = 790, //UNUSED
    MUS_GS_RADIOLULLABY = 791,
    MUS_GS_RADIOMARCH = 792, //UNUSED
    MUS_GS_RADIOOAK = 793, //UNUSED
    MUS_GS_RESULTS1 = 794, //UNUSED
    MUS_GS_RESULTS2 = 795, //UNUSED
    MUS_GS_RESULTS3 = 796, //UNUSED
    MUS_GS_RIVAL = 797,
    MUS_GS_ROCKET = 798,
    MUS_GS_RUINS = 799, //UNUSED
    MUS_GS_SAFFRON = 800, //UNUSED
    MUS_GS_SHIP = 801, //UNUSED
    MUS_GS_SURFING = 802,
    MUS_GS_THEEND = 803, //UNUSED
    MUS_GS_TITLE = 804, //UNUSED
    MUS_GS_TOWER1 = 805,
    MUS_GS_TOWER2 = 806,
    MUS_GS_TOWER3 = 807,
    MUS_GS_TRADE = 808, //UNUSED
    MUS_GS_VERMILION = 809,
    MUS_GS_VICTORY1 = 810, //UNUSED
    MUS_GS_VICTORY2 = 811, //UNUSED
    MUS_GS_VICTORY3 = 812, //UNUSED
    MUS_GS_VIOLET = 813,
    MUS_GS_VROAD = 814,
    MUS_RB_1 = 815,
    MUS_RB_10 = 816,
    MUS_RB_12 = 817,
    MUS_RB_24 = 818,
    MUS_RB_AROUND = 819,
    MUS_RB_BATTLE1 = 820,
    MUS_RB_VS_TRAINER = 821,
    MUS_RB_VS_LEADER = 822,
    MUS_RB_BATTLE4 = 823,
    MUS_RB_BIKE = 824,
    MUS_RB_CAUGHT = 825, //UNUSED
    MUS_RB_CELADON = 826,
    MUS_RB_CENTER = 827,
    MUS_RB_CERULEAN = 828,
    MUS_RB_CINNABAR = 829,
    MUS_RB_CORNER = 830, //UNUSED
    MUS_RB_CREDITS = 831, //UNUSED
    MUS_RB_ENC1 = 832, //UNUSED
    MUS_RB_ENC2 = 833, //UNUSED
    MUS_RB_ENC3 = 834, //UNUSED
    MUS_RB_EVOLVING = 835,
    MUS_RB_FOREST = 836,
    MUS_RB_GYM = 837,
    MUS_RB_HALL = 838, //UNUSED
    MUS_RB_HEAL = 839, //UNUSED
    MUS_RB_HIDEOUT = 840, //UNUSED
    MUS_RB_INDIGO = 841,
    MUS_RB_INTRO = 842, //UNUSED
    MUS_RB_ITEM1 = 843, //UNUSED
    MUS_RB_ITEM2 = 844, //UNUSED
    MUS_RB_ITEM3 = 845, //UNUSED
    MUS_RB_LAB = 846,
    MUS_RB_LAVENDER = 847, //UNUSED
    MUS_RB_LEVELUP = 848, //UNUSED
    MUS_RB_MANSION = 849,
    MUS_RB_MTMOON = 850,
    MUS_RB_OAK = 851, //UNUSED
    MUS_RB_PALLET = 852,
    MUS_RB_POKEDEX = 853, //UNUSED
    MUS_RB_RIVAL = 854,
    MUS_RB_SHIP = 855,
    MUS_RB_SILPHCO = 856,
    MUS_RB_SURFING = 857,
    MUS_RB_TITLE = 858, //UNUSED
    MUS_RB_TOWER = 859,
    MUS_RB_VERMILION = 860,
    MUS_RB_VICTORY1 = 861, //UNUSED
    MUS_RB_VICTORY2 = 862, //UNUSED
    MUS_RB_VICTORY3 = 863, //UNUSED
    MUS_RB_VIRIDIAN = 864,
    MUS_DP_GYM = 865,
    MUS_DP_SANDGEM_NIGHT = 866,
    MUS_GS_VS_KANTO_LEADER_BLAINE = 867,
    MUS_GS_VS_KANTO_LEADER_JANINE_KOGA = 868,
    MUS_GS_VS_KANTO_LEADER_ERIKA = 869,
    MUS_GS_VS_KANTO_LEADER_MISTY_SURGE = 870,
    MUS_GS_VS_KANTO_LEADER_SABRINA = 871,
    MUS_GS_VS_KANTO_LEADER_BROCK = 872,
    MUS_COLOSSEUM_BATTLE_FANFARE_1_V1_1 = 873, //UNUSED
    MUS_COLOSSEUM_BATTLE_FANFARE_1 = 874, //UNUSED
    MUS_COLOSSEUM_PYRITE_TOWN = 875,
    MUS_COLOSSEUM_RELIC_STONE_SHRINE = 876,
    MUS_COLOSSEUM_STORY_MODE_NORMAL_BATTLE_ARRANGED = 877, //UNUSED
    MUS_COLOSSEUM_VS_CIPHER_ADMIN = 878,
    MUS_COLOSSEUM_BATTLE2 = 879, //UNUSED
    MUS_COLOSSEUM_BATTLE5 = 880, //UNUSED
    MUS_COLOSSEUM_BATTLE6 = 881, //UNUSED
    MUS_COLOSSEUM_BATTLE7 = 882, //UNUSED
    MUS_COLOSSEUM_BATTLE8 = 883, //UNUSED
    MUS_COLOSSEUM_BATTLE9 = 884, //UNUSED
    MUS_COLOSSEUM_COUNTRY = 885,
    MUS_COLOSSEUM_DARKSIDE4 = 886, //UNUSED
    MUS_COLOSSEUM_DARKSIDE = 887, //UNUSED
    MUS_COLOSSEUM_DARKUNDER = 888,
    MUS_COLOSSEUM_DUNGEON = 889,
    MUS_COLOSSEUM_MT_BATTLE = 890,
    MUS_COLOSSEUM_TRETRE = 891,
    MUS_COLOSSEUM_VIRTUAL = 892, //UNUSED
    MUS_COLOSSEUM_WATERCITY = 893,
    MUS_COLOSSEUM_WIND_ATMOS_LOOP = 894, //UNUSED
    MUS_COLOSSEUM_WINDYCITY = 895, //UNUSED
    MUS_COLOSSEUM_WORLDMAP2 = 896, //UNUSED
    MUS_COLOSSEUM_WORLDMAP = 897, //UNUSED
    MUS_PMD_VS_DIALGA = 898,
    MUS_HG_ROUTE47 = 899,
    MUS_DP_ROUTE_216 = 900, //UNUSED
    MUS_DP_SNOWPOINT = 901, //UNUSED
    MUS_UNOVA_ROUTE_22 = 902,
    MUS_UNOVA_ABYSSAL_RUINS = 903, //UNUSED
    MUS_UNOVA_ROUTE_23 = 904, //UNUSED
    MUS_UNOVA_ROUTE_1 = 905,
    MUS_UNOVA_ROUTE_10 = 906, //UNUSED
    MUS_UNOVA_FIRST_DAY = 907, //UNUSED
    MUS_DP_ROUTE_201 = 908,
    MUS_UNOVA_HUMILAU_CITY = 909,
    MUS_HG_ROUTE26 = 910, //UNUSED
    MUS_UNOVA_ANVILLE_TOWN = 911,
    MUS_HG_CHERRYGROVE = 912,
    MUS_UNOVA_LOSTORN_FOREST = 913,
    MUS_UNOVA_LACONUSA_TOWN = 914,
    MUS_UNOVA_ASPERTIA_CITY = 915,
    MUS_UNOVA_CHARGESTONE_CAVE = 916, //UNUSED
    MUS_FLOCCESY_RANCH = 917,
    MUS_DP_FIGHT_AREA_DAY = 918,
    MUS_DP_SURF = 919,
    MUS_BW_SURF = 920,
    MUS_HG_VIOLET = 921,
    MUS_HG_PALLET = 922,
    MUS_HG_POKE_CENTER = 923,
    MUS_HG_POKEMON_LEAGUE = 924,
    MUS_BW_POKE_CENTER = 925,
    MUS_BW_POKE_MART = 926,
    MUS_BW_POKEMON_LEAGUE = 927,
    MUS_DP_POKE_CENTER = 928,
    MUS_DP_POKE_MART = 929,
    MUS_HG_ROUTE1 = 930, //UNUSED
    MUS_HG_ROUTE3 = 931,
    MUS_HG_ROUTE11 = 932, //UNUSED
    MUS_HG_ROUTE24 = 933, //UNUSED
    MUS_HG_ROUTE29 = 934,
    MUS_HG_ROUTE30 = 935,
    MUS_HG_ROUTE34 = 936,
    MUS_HG_ROUTE38 = 937,
    MUS_HG_ROUTE42 = 938, //UNUSED
    MUS_HG_CYCLING = 939,
    MUS_HG_POKE_MART = 940,
    MUS_HG_NEWBARK = 941,
    MUS_HG_ROCKET_TAKEOVER = 942,
    MUS_DP_GALACTIC_ETERNA_BUILDING = 943, //UNUSED
    MUS_DP_STARK_MOUNTAIN = 944,
    MUS_HG_VERMILLION = 945,
    MUS_HG_BELL_TOWER = 946,
    MUS_HG_SPROUT_TOWER = 947,
    MUS_HG_TEAM_ROCKET_HQ = 948,
    MUS_HG_ICE_PATH = 949,
    MUS_PL_DISTORTION_WORLD = 950,
    MUS_HG_GYM = 951,
    MUS_HG_GOLDENROD = 952,
    MUS_HG_SURF = 953,
    MUS_HG_UNION_CAVE = 954,
    MUS_DP_VS_GYM_LEADER = 955,
    MUS_VS_FINAL_POKEMON_RB = 956,
    MUS_VS_FINAL_POKEMON_GS = 957,
    MUS_VS_FINAL_POKEMON_BLAINE = 958,
    MUS_HG_BUG_CATCHING_CONTEST = 959,
    MUS_DP_FOLLOW_ME = 960,
    MUS_HG_FOLLOW_ME_2 = 961,
    MUS_BW_N_CASTLE = 962,
    MUS_BW_DRIFTVEIL = 963,
    MUS_BW_CYCLING = 964,
    MUS_BW_ROUTE12_AUTUMN = 965,
    MUS_BW_ROUTE4_SUMMER = 966,
    MUS_BW_ROUTE2_SUMMER = 967,
    MUS_BW_TROUBLE = 968,
    MUS_BW_RELIC_SONG = 969,
    MUS_HG_ELM_LAB = 970,
    MUS_BW_JUNIPER_LAB = 971,
    MUS_BW_ICIRRUS = 972,
    MUS_BW_NUVEMA = 973,
    MUS_BW_FOLLOW_ME_2 = 974,
    MUS_BW_TUBELINE_BRIDGE = 975,
    MUS_DP_UNDERGROUND = 976,
    MUS_DP_VICTORY_ROAD = 977,
    MUS_HG_VICTORY_ROAD = 978,
    MUS_BW_BLACK_CITY = 979,
    MUS_BW_SKYARROW_BRIDGE = 980,
    MUS_DP_RIVAL = 981,
    MUS_HG_ENCOUNTER_RIVAL = 982,
    MUS_BW_CHEREN = 983,
    MUS_BW_BIANCA = 984,
    MUS_BW_VICTORY_ROAD = 985,
    MUS_BW_SAGE = 986,
    MUS_BW_CASTELIA = 987,
    MUS_HG_RIVAL_EXIT = 988, //UNUSED
    MUS_DP_VS_GALACTIC_COMMANDER = 989,
    MUS_BW_VS_TEAM_PLASMA = 990,
    MUS_PMD_WIGGLYTUFFS_GUILD = 991,
    MUS_PMD_AT_THE_END_OF_THE_DAY = 992,
    MUS_PMD_TEMPORAL_TOWER = 993,
    MUS_PMD_THROUGH_THE_SEA_OF_TIME = 994,
    MUS_PMD_FOGGY_FOREST = 995,
    MUS_PMD_A_WISH_FOR_PEACE = 996,
    MUS_PMD_JOB_CLEAR = 997,
    MUS_PMD_CRAGGY_COAST = 998,
    MUS_PMD_DEEP_DARK_CRATER = 999,
    MUS_PMD_ON_THE_BEACH_AT_DUSK = 1000,
    MUS_PMD_TOP_MENU_THEME = 1001,
    MUS_PMD_TIME_GEAR = 1002,
    MUS_PMD_HEARTWARMING = 1003,
    MUS_PMD_TREASURE_TOWN = 1004,
    MUS_PMD_DRENCHED_BLUFF = 1005,
    MUS_PMD_APPLE_WOODS = 1006,
    MUS_PMD_SOUTHERN_JUNGLE = 1007,
    MUS_PMD_DO_YOUR_BEST_AS_ALWAYS = 1008,
    MUS_PMD_KECLEONS_SHOP = 1009,
    MUS_PMD_GOODNIGHT = 1010,
    MUS_PMD_SPACIAL_CLIFFS = 1011,
    MUS_PMD_TEMPORAL_SPIRE = 1012,
    MUS_PMD_WIGGLYTUFFS_GUILD_REMIX = 1013,
    MUS_PMD_PELIPPER_ISLAND = 1014,
    MUS_PMD_SKY_PEAK_FOREST = 1015,
    MUS_PMD_ENDING_THEME = 1016,
    MUS_PMD_HIDDEN_LAND = 1017,
    MUS_PMD_SHAYMIN_VILLAGE = 1018,
    MUS_PMD_ILLUSION_STONE_CHAMBER = 1019,
    MUS_PMD_FAR_AMP_PLAINS = 1020,
    MUS_PMD_IN_THE_FUTURE = 1021,
    MUS_PMD_A_FUN_EXPLORATION = 1022,
    MUS_PMD_TEAM_CHARMS_THEME = 1023,
    MUS_PMD_SPINDAS_CAFE = 1024,
    MUS_PMD_VAST_ICE_MOUNTAIN_PEAK = 1025,
    MUS_EVER_GRANDE_INTERNAL = 1026,

// These PH_* constants are phoneme sounds used by the "bard" NPC (see src/bard_music.c and src/mauville_old_man.c).
// Each comes in a triplet of PH_*_BLEND, PH_*_HELD, and PH_*_SOLO, and the name of each triplet incorporates the English phonetic sound it represents.
    PH_TRAP_BLEND = 559,
    PH_TRAP_HELD,
    PH_TRAP_SOLO,
    PH_FACE_BLEND,
    PH_FACE_HELD,
    PH_FACE_SOLO,
    PH_CLOTH_BLEND,
    PH_CLOTH_HELD,
    PH_CLOTH_SOLO,
    PH_DRESS_BLEND,
    PH_DRESS_HELD,
    PH_DRESS_SOLO,
    PH_FLEECE_BLEND,
    PH_FLEECE_HELD,
    PH_FLEECE_SOLO,
    PH_KIT_BLEND,
    PH_KIT_HELD,
    PH_KIT_SOLO,
    PH_PRICE_BLEND,
    PH_PRICE_HELD,
    PH_PRICE_SOLO,
    PH_LOT_BLEND,
    PH_LOT_HELD,
    PH_LOT_SOLO,
    PH_GOAT_BLEND,
    PH_GOAT_HELD,
    PH_GOAT_SOLO,
    PH_THOUGHT_BLEND,
    PH_THOUGHT_HELD,
    PH_THOUGHT_SOLO,
    PH_CHOICE_BLEND,
    PH_CHOICE_HELD,
    PH_CHOICE_SOLO,
    PH_MOUTH_BLEND,
    PH_MOUTH_HELD,
    PH_MOUTH_SOLO,
    PH_FOOT_BLEND,
    PH_FOOT_HELD,
    PH_FOOT_SOLO,
    PH_GOOSE_BLEND,
    PH_GOOSE_HELD,
    PH_GOOSE_SOLO,
    PH_STRUT_BLEND,
    PH_STRUT_HELD,
    PH_STRUT_SOLO,
    PH_CURE_BLEND,
    PH_CURE_HELD,
    PH_CURE_SOLO,
    PH_NURSE_BLEND,
    PH_NURSE_HELD,
    PH_NURSE_SOLO,

    MUS_ROUTE118        = 0x7FFF,

    MUS_NONE            = 0xFFFF,
};

#define END_SE              SE_M_HYPER_BEAM_GEN1
#define START_MUS           MUS_LITTLEROOT_TEST
#define END_MUS             MUS_DP_VS_GALACTIC_COMMANDER
#define START_EMERALD_MUS   MUS_LITTLEROOT_TEST
#define END_EMERALD_MUS     MUS_VS_ELITE_FOUR
#define START_RG_MUS        MUS_RG_FOLLOW_ME
#define END_RG_MUS          MUS_RG_TEACHY_TV_MENU
#define START_TAGMANIA_MUS  MUS_VS_SINNOH_BRAIN
#define END_TAGMANIA_MUS    END_MUS
#define FIRST_PHONEME_SONG  PH_TRAP_BLEND
#define LAST_PHONEME_SONG   PH_NURSE_SOLO

#define NUM_PHONEME_SONGS           (LAST_PHONEME_SONG - FIRST_PHONEME_SONG + 1)
#define PHONEME_ID(song)            ((song) - FIRST_PHONEME_SONG)
#define PHONEME_ID_NONE             0xFF

#endif  // GUARD_CONSTANTS_SONGS_H
