#include "global.h"
#include "test/battle.h"

#define AI_FRAME_CEILING_SINGLES_NO_FLAGS                       2
#define AI_FRAME_CEILING_SINGLES_SMART_TRAINER                  7
#define AI_FRAME_CEILING_DOUBLES_NO_FLAGS                       14
#define AI_FRAME_CEILING_DOUBLES_SMART_TRAINER                  32
#define AI_FRAME_CEILING_STEVEN_MULTI                           21
#define AI_FRAME_CEILING_STEVEN_MULTI_SMART_TRAINER             25
#define AI_FRAME_CEILING_CHECK                                  FALSE // If TRUE, forces all thinking time tests to fail. Useful for printing all actual frame times to console by running the tests

#define AI_FRAME_CEILING_DOUBLES_TAG_TRAINER                    42
#define AI_FRAME_CEILING_DOUBLES_PARTNER_TRAINER                43
#define AI_FRAME_CEILING_STEVEN_MULTI_TAG_TRAINER               38
#define AI_FRAME_CEILING_STEVEN_MULTI_PARTNER_TRAINER           40
#define AI_FRAME_CEILING_STEVEN_2VS1_TAG_TRAINER                54
#define AI_FRAME_CEILING_STEVEN_2VS1_PARTNER_TRAINER            56

AI_SINGLE_BATTLE_TEST("AI thinking time doesn't explode (singles, no flags)")
{
    GIVEN {
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
    } WHEN {
        TURN { }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_SINGLES_NO_FLAGS);
    }
}

AI_SINGLE_BATTLE_TEST("AI thinking time doesn't explode (singles, smart)")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_SMART_TRAINER);
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
    } WHEN {
        TURN { }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_SINGLES_SMART_TRAINER);
    }
}

AI_DOUBLE_BATTLE_TEST("AI thinking time doesn't explode (doubles, no flags)")
{
    GIVEN {
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
    } WHEN {
        TURN { }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_DOUBLES_NO_FLAGS);
    }
}

AI_DOUBLE_BATTLE_TEST("AI thinking time doesn't explode (doubles, smart)")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_SMART_TRAINER);
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
    } WHEN {
        TURN { }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_DOUBLES_SMART_TRAINER);
    }
}

AI_DOUBLE_BATTLE_TEST("AI thinking time doesn't explode (doubles, Tag Trainer)")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_TAG_TRAINER);
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
    } WHEN {
        TURN { }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_DOUBLES_TAG_TRAINER);
    }
}

AI_DOUBLE_BATTLE_TEST("AI thinking time doesn't explode (doubles, Partner Trainer)")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_PARTNER_TRAINER);
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        PLAYER(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_CELEBRATE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_FLING); }
    } WHEN {
        TURN { }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_DOUBLES_PARTNER_TRAINER);
    }
}

AI_MULTI_BATTLE_TEST("AI thinking time doesn't explode (Steven multi)")
{
    GIVEN {
        BATTLER_AI_FLAGS(playerRight, AI_FLAG_BASIC_TRAINER);
        BATTLER_AI_FLAGS(opponentLeft, AI_FLAG_BASIC_TRAINER);
        BATTLER_AI_FLAGS(opponentRight, AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_ZIGZAGOON) { Level(100); Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_CELEBRATE); }
        PARTNER(SPECIES_METANG) { Level(42); Moves(MOVE_CELEBRATE, MOVE_PSYCHIC, MOVE_REFLECT, MOVE_METAL_CLAW); }
        PARTNER(SPECIES_SKARMORY) { Level(43); Moves(MOVE_TOXIC, MOVE_AERIAL_ACE, MOVE_PROTECT, MOVE_STEEL_WING); }
        PARTNER(SPECIES_AGGRON) { Level(44); Moves(MOVE_THUNDER, MOVE_PROTECT, MOVE_SOLARBEAM, MOVE_DRAGON_CLAW); }
        OPPONENT_A(SPECIES_MIGHTYENA) { Level(42); Moves(MOVE_CELEBRATE, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_A(SPECIES_CROBAT) { Level(43); Moves(MOVE_HAZE, MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD); }
        OPPONENT_A(SPECIES_CAMERUPT) { Level(44); Moves(MOVE_YAWN, MOVE_TAKE_DOWN, MOVE_CURSE, MOVE_EARTH_POWER); }
        OPPONENT_B(SPECIES_CAMERUPT) { Level(36); Moves(MOVE_TAKE_DOWN, MOVE_CELEBRATE, MOVE_EARTH_POWER, MOVE_LAVA_PLUME); }
        OPPONENT_B(SPECIES_MIGHTYENA) { Level(38); Moves(MOVE_TAUNT, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_B(SPECIES_GOLBAT) { Level(40); Moves(MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD, MOVE_POISON_FANG); }
        TIE_BREAK_SCORE(RNG_AI_SCORE_TIE_DOUBLES_MOVE, SCORE_TIE_HI, 0);
    } WHEN {
        TURN { EXPECT_MOVE(playerRight, MOVE_REFLECT); }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_STEVEN_MULTI);
    }
}

AI_MULTI_BATTLE_TEST("AI thinking time doesn't explode (Steven multi, smart)")
{
    GIVEN {
        BATTLER_AI_FLAGS(playerRight, AI_FLAG_SMART_TRAINER);
        BATTLER_AI_FLAGS(opponentLeft, AI_FLAG_SMART_TRAINER);
        BATTLER_AI_FLAGS(opponentRight, AI_FLAG_SMART_TRAINER);
        PLAYER(SPECIES_ZIGZAGOON) { Level(100); Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_CELEBRATE); }
        PARTNER(SPECIES_METANG) { Level(42); Moves(MOVE_CELEBRATE, MOVE_PSYCHIC, MOVE_REFLECT, MOVE_METAL_CLAW); }
        PARTNER(SPECIES_SKARMORY) { Level(43); Moves(MOVE_TOXIC, MOVE_AERIAL_ACE, MOVE_PROTECT, MOVE_STEEL_WING); }
        PARTNER(SPECIES_AGGRON) { Level(44); Moves(MOVE_THUNDER, MOVE_PROTECT, MOVE_SOLARBEAM, MOVE_DRAGON_CLAW); }
        OPPONENT_A(SPECIES_MIGHTYENA) { Level(42); Moves(MOVE_CELEBRATE, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_A(SPECIES_CROBAT) { Level(43); Moves(MOVE_HAZE, MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD); }
        OPPONENT_A(SPECIES_CAMERUPT) { Level(44); Moves(MOVE_YAWN, MOVE_TAKE_DOWN, MOVE_CURSE, MOVE_EARTH_POWER); }
        OPPONENT_B(SPECIES_CAMERUPT) { Level(36); Moves(MOVE_TAKE_DOWN, MOVE_CELEBRATE, MOVE_EARTH_POWER, MOVE_LAVA_PLUME); }
        OPPONENT_B(SPECIES_MIGHTYENA) { Level(38); Moves(MOVE_TAUNT, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_B(SPECIES_GOLBAT) { Level(40); Moves(MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD, MOVE_POISON_FANG); }
        TIE_BREAK_SCORE(RNG_AI_SCORE_TIE_DOUBLES_MOVE, SCORE_TIE_HI, 0);
    } WHEN {
        TURN { EXPECT_MOVE(playerRight, MOVE_REFLECT); }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_STEVEN_MULTI_SMART_TRAINER);
    }
}

AI_MULTI_BATTLE_TEST("AI thinking time doesn't explode (Steven multi, Tag Trainer)")
{
    GIVEN {
        BATTLER_AI_FLAGS(playerRight, AI_FLAG_TAG_TRAINER);
        BATTLER_AI_FLAGS(opponentLeft, AI_FLAG_TAG_TRAINER);
        BATTLER_AI_FLAGS(opponentRight, AI_FLAG_TAG_TRAINER);
        PLAYER(SPECIES_ZIGZAGOON) { Level(100); Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_CELEBRATE); }
        PARTNER(SPECIES_METANG) { Level(42); Moves(MOVE_CELEBRATE, MOVE_PSYCHIC, MOVE_REFLECT, MOVE_METAL_CLAW); }
        PARTNER(SPECIES_SKARMORY) { Level(43); Moves(MOVE_TOXIC, MOVE_AERIAL_ACE, MOVE_PROTECT, MOVE_STEEL_WING); }
        PARTNER(SPECIES_AGGRON) { Level(44); Moves(MOVE_THUNDER, MOVE_PROTECT, MOVE_SOLARBEAM, MOVE_DRAGON_CLAW); }
        OPPONENT_A(SPECIES_MIGHTYENA) { Level(42); Moves(MOVE_CELEBRATE, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_A(SPECIES_CROBAT) { Level(43); Moves(MOVE_HAZE, MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD); }
        OPPONENT_A(SPECIES_CAMERUPT) { Level(44); Moves(MOVE_YAWN, MOVE_TAKE_DOWN, MOVE_CURSE, MOVE_EARTH_POWER); }
        OPPONENT_B(SPECIES_CAMERUPT) { Level(36); Moves(MOVE_TAKE_DOWN, MOVE_CELEBRATE, MOVE_EARTH_POWER, MOVE_LAVA_PLUME); }
        OPPONENT_B(SPECIES_MIGHTYENA) { Level(38); Moves(MOVE_TAUNT, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_B(SPECIES_GOLBAT) { Level(40); Moves(MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD, MOVE_POISON_FANG); }
        TIE_BREAK_SCORE(RNG_AI_SCORE_TIE_DOUBLES_MOVE, SCORE_TIE_HI, 0);
    } WHEN {
        TURN { EXPECT_MOVE(playerRight, MOVE_REFLECT); }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_STEVEN_MULTI_TAG_TRAINER);
    }
}

AI_MULTI_BATTLE_TEST("AI thinking time doesn't explode (Steven multi, Partner Trainer)")
{
    GIVEN {
        BATTLER_AI_FLAGS(playerRight, AI_FLAG_PARTNER_TRAINER);
        BATTLER_AI_FLAGS(opponentLeft, AI_FLAG_PARTNER_TRAINER);
        BATTLER_AI_FLAGS(opponentRight, AI_FLAG_PARTNER_TRAINER);
        PLAYER(SPECIES_ZIGZAGOON) { Level(100); Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_CELEBRATE); }
        PARTNER(SPECIES_METANG) { Level(42); Moves(MOVE_CELEBRATE, MOVE_PSYCHIC, MOVE_REFLECT, MOVE_METAL_CLAW); }
        PARTNER(SPECIES_SKARMORY) { Level(43); Moves(MOVE_TOXIC, MOVE_AERIAL_ACE, MOVE_PROTECT, MOVE_STEEL_WING); }
        PARTNER(SPECIES_AGGRON) { Level(44); Moves(MOVE_THUNDER, MOVE_PROTECT, MOVE_SOLARBEAM, MOVE_DRAGON_CLAW); }
        OPPONENT_A(SPECIES_MIGHTYENA) { Level(42); Moves(MOVE_CELEBRATE, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_A(SPECIES_CROBAT) { Level(43); Moves(MOVE_HAZE, MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD); }
        OPPONENT_A(SPECIES_CAMERUPT) { Level(44); Moves(MOVE_YAWN, MOVE_TAKE_DOWN, MOVE_CURSE, MOVE_EARTH_POWER); }
        OPPONENT_B(SPECIES_CAMERUPT) { Level(36); Moves(MOVE_TAKE_DOWN, MOVE_CELEBRATE, MOVE_EARTH_POWER, MOVE_LAVA_PLUME); }
        OPPONENT_B(SPECIES_MIGHTYENA) { Level(38); Moves(MOVE_TAUNT, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_B(SPECIES_GOLBAT) { Level(40); Moves(MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD, MOVE_POISON_FANG); }
        TIE_BREAK_SCORE(RNG_AI_SCORE_TIE_DOUBLES_MOVE, SCORE_TIE_HI, 0);
    } WHEN {
        TURN { EXPECT_MOVE(playerRight, MOVE_REFLECT); }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_STEVEN_MULTI_PARTNER_TRAINER);
    }
}

AI_TWO_VS_ONE_BATTLE_TEST("AI thinking time doesn't explode (Steven 2v1, Tag Trainer)")
{
    GIVEN {
        BATTLER_AI_FLAGS(playerRight, AI_FLAG_TAG_TRAINER);
        BATTLER_AI_FLAGS(opponentLeft, AI_FLAG_TAG_TRAINER);
        BATTLER_AI_FLAGS(opponentRight, AI_FLAG_TAG_TRAINER);
        PLAYER(SPECIES_ZIGZAGOON) { Level(100); Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_CELEBRATE); }
        PARTNER(SPECIES_METANG) { Level(42); Moves(MOVE_CELEBRATE, MOVE_PSYCHIC, MOVE_REFLECT, MOVE_METAL_CLAW); }
        PARTNER(SPECIES_SKARMORY) { Level(43); Moves(MOVE_TOXIC, MOVE_AERIAL_ACE, MOVE_PROTECT, MOVE_STEEL_WING); }
        PARTNER(SPECIES_AGGRON) { Level(44); Moves(MOVE_THUNDER, MOVE_PROTECT, MOVE_SOLARBEAM, MOVE_DRAGON_CLAW); }
        OPPONENT_A(SPECIES_MIGHTYENA) { Level(42); Moves(MOVE_CELEBRATE, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_A(SPECIES_CAMERUPT) { Level(36); Moves(MOVE_TAKE_DOWN, MOVE_CELEBRATE, MOVE_EARTH_POWER, MOVE_LAVA_PLUME); }
        OPPONENT_A(SPECIES_CROBAT) { Level(43); Moves(MOVE_HAZE, MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD); }
        OPPONENT_A(SPECIES_CAMERUPT) { Level(44); Moves(MOVE_YAWN, MOVE_TAKE_DOWN, MOVE_CURSE, MOVE_EARTH_POWER); }
        OPPONENT_A(SPECIES_MIGHTYENA) { Level(38); Moves(MOVE_TAUNT, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_A(SPECIES_GOLBAT) { Level(40); Moves(MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD, MOVE_POISON_FANG); }
        TIE_BREAK_SCORE(RNG_AI_SCORE_TIE_DOUBLES_MOVE, SCORE_TIE_HI, 0);
    } WHEN {
        TURN { EXPECT_MOVE(playerRight, MOVE_REFLECT); }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_STEVEN_2VS1_TAG_TRAINER);
    }
}

AI_TWO_VS_ONE_BATTLE_TEST("AI thinking time doesn't explode (Steven 2v1, Partner Trainer)")
{
    GIVEN {
        BATTLER_AI_FLAGS(playerRight, AI_FLAG_PARTNER_TRAINER);
        BATTLER_AI_FLAGS(opponentLeft, AI_FLAG_PARTNER_TRAINER);
        BATTLER_AI_FLAGS(opponentRight, AI_FLAG_PARTNER_TRAINER);
        PLAYER(SPECIES_ZIGZAGOON) { Level(100); Moves(MOVE_DOUBLE_EDGE, MOVE_BELLY_DRUM, MOVE_FLAIL, MOVE_CELEBRATE); }
        PARTNER(SPECIES_METANG) { Level(42); Moves(MOVE_CELEBRATE, MOVE_PSYCHIC, MOVE_REFLECT, MOVE_METAL_CLAW); }
        PARTNER(SPECIES_SKARMORY) { Level(43); Moves(MOVE_TOXIC, MOVE_AERIAL_ACE, MOVE_PROTECT, MOVE_STEEL_WING); }
        PARTNER(SPECIES_AGGRON) { Level(44); Moves(MOVE_THUNDER, MOVE_PROTECT, MOVE_SOLARBEAM, MOVE_DRAGON_CLAW); }
        OPPONENT_A(SPECIES_MIGHTYENA) { Level(42); Moves(MOVE_CELEBRATE, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_A(SPECIES_CAMERUPT) { Level(36); Moves(MOVE_TAKE_DOWN, MOVE_CELEBRATE, MOVE_EARTH_POWER, MOVE_LAVA_PLUME); }
        OPPONENT_A(SPECIES_CROBAT) { Level(43); Moves(MOVE_HAZE, MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD); }
        OPPONENT_A(SPECIES_CAMERUPT) { Level(44); Moves(MOVE_YAWN, MOVE_TAKE_DOWN, MOVE_CURSE, MOVE_EARTH_POWER); }
        OPPONENT_A(SPECIES_MIGHTYENA) { Level(38); Moves(MOVE_TAUNT, MOVE_SCARY_FACE, MOVE_ASSURANCE, MOVE_SWAGGER); }
        OPPONENT_A(SPECIES_GOLBAT) { Level(40); Moves(MOVE_BITE, MOVE_AIR_CUTTER, MOVE_QUICK_GUARD, MOVE_POISON_FANG); }
        TIE_BREAK_SCORE(RNG_AI_SCORE_TIE_DOUBLES_MOVE, SCORE_TIE_HI, 0);
    } WHEN {
        TURN { EXPECT_MOVE(playerRight, MOVE_REFLECT); }
    } THEN {
        EXPECT_LE(gBattleStruct->aiDelayFrames, AI_FRAME_CEILING_CHECK ? 0 : AI_FRAME_CEILING_STEVEN_2VS1_PARTNER_TRAINER);
    }
}
